// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,true:8, false:8, null:14}
export const parser = LRParser.deserialize({
  version: 14,
  states: "bOVQPOOOOQO'#Cg'#CgQOQPOO",
  stateData: "q~OYOS~OQPORPOSPOTPOUPOVPO~ORQY[Y~",
  goto: "`[PPPPPPPPPPP]RQO",
  nodeNames: "⚠ Expression IntegerLiteral FloatingPointLiteral BooleanLiteral CharacterLiteral StringLiteral null",
  maxTerm: 12,
  nodeProps: [
    ["isolate", -2,5,6,""]
  ],
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "2O~RkX^!vpq!vrs#ktu$uwx%j!O!P'p!Q!R)w!R![+m#R#S$u#T#o$u#y#z!v$f$g!v$g#BY$u#BY#BZ0]#BZ$IS$u$IS$I_0]$I_$I|$u$I|$JO0]$JO$JT$u$JT$JU0]$JU$KV$u$KV$KW0]$KW&FU$u&FU&FV0]&FV;'S$u;'S;=`%d<%lO$u~!{YY~X^!vpq!v#y#z!v$f$g!v#BY#BZ!v$IS$I_!v$I|$JO!v$JT$JU!v$KV$KW!v&FU&FV!v~#nWOY#kZr#krs$Ws#O#k#O#P$]#P;'S#k;'S;=`$o<%lO#k~$]OU~~$`TOY#kYZ#kZ;'S#k;'S;=`$o<%lO#k~$rP;=`<%l#k~$zW[~tu$u!Q![$u!c!}$u#R#S$u#T#o$u$g;'S$u;'S;=`%d<%lO$u~%gP;=`<%l$u~%mVOY&SZw&Sx#O&S#O#P&_#P;'S&S;'S;=`'j<%lO&S~&VPwx&Y~&_OT~~&bWOY&zZw&zwx&Sx#O&z#O#P&S#P;'S&z;'S;=`'d<%lO&z~&}VOY&zZw&zwx&Yx#O&z#P;'S&z;'S;=`'d<%lO&z~'gP;=`<%l&z~'mP;=`<%l&S~'sP!Q!['v~'{WR~!Q!['v!f!g(e!g!h(j!h!i(e#R#S)n#W#X(e#X#Y(j#Y#Z(e~(jOR~~(mR{|(v}!O(v!Q![(|~(yP!Q![(|~)RUR~!Q![(|!f!g(e!h!i(e#R#S)e#W#X(e#Y#Z(e~)hQ!Q![(|#R#S)e~)qQ!Q!['v#R#S)n~)|aQ~!O!P+R!Q![+m!d!e,s!f!g(e!g!h(j!h!i(e!n!o,e!q!r-b!z!{-y#R#S,j#U#V,s#W#X(e#X#Y(j#Y#Z(e#`#a,e#c#d-b#l#m-y~+WVR~!Q!['v!f!g(e!g!h(j!h!i(e#W#X(e#X#Y(j#Y#Z(e~+rZQ~!O!P+R!Q![+m!f!g(e!g!h(j!h!i(e!n!o,e#R#S,j#W#X(e#X#Y(j#Y#Z(e#`#a,e~,jOQ~~,mQ!Q![+m#R#S,j~,vQ!Q!R,|!R!S,|~-RTQ~!Q!R,|!R!S,|!n!o,e#R#S,s#`#a,e~-eP!Q!Y-h~-mSQ~!Q!Y-h!n!o,e#R#S-b#`#a,e~-|S!O!P.Y!Q![.{!c!i.{#T#Z.{~.]R!Q![.f!c!i.f#T#Z.f~.iU!Q![.f!c!i.f!r!s(j#R#S.Y#T#Z.f#d#e(j~/QXQ~!O!P/m!Q![.{!c!i.{!n!o,e!r!s(j#R#S0P#T#Z.{#`#a,e#d#e(j~/pT!Q![.f!c!i.f!r!s(j#T#Z.f#d#e(j~0SR!Q![.{!c!i.{#T#Z.{~0dhY~[~X^!vpq!vtu$u!Q![$u!c!}$u#R#S$u#T#o$u#y#z!v$f$g!v$g#BY$u#BY#BZ0]#BZ$IS$u$IS$I_0]$I_$I|$u$I|$JO0]$JO$JT$u$JT$JU0]$JU$KV$u$KV$KW0]$KW&FU$u&FU&FV0]&FV;'S$u;'S;=`%d<%lO$u",
  tokenizers: [0],
  topRules: {"Expression":[0,1]},
  specialized: [{term: 12, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 27
})
