// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,true:30, false:30, null:36, byte:48, short:48, int:48, long:48, char:48, float:48, double:48, boolean:48}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%^OVQPOOQwQQOOOOQO'#C}'#C}O!lQPO'#CoOOQO'#C|'#C|OVQPO'#CpOOQO'#Cx'#CxOOQO'#C`'#C`OOQO'#Cc'#CcOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xO!sQQO,59ZO!zQPO,59_OOQO,59[,59[O#wQQO1G.dO$vQQO1G.dO$}QQO1G.dO%|QQO1G.dO&TQQO1G.dO&sQQO1G.dO(RQQO1G.dOOQO1G.d1G.dO(YQQO1G.dOOQO1G.u1G.uOVQPO1G.yOOQO7+$e7+$e",
  stateData: "(g~OkOS~OYTO]QO^QO_QO`QOaQObQOeTOfTOsRO~ORXOTYOUZOW]OX^OY_OZ`O[aOmVOnVOoWO~OhcO~PVOtnO~PwOtoO~OY_OZ`ORQiTQiUQiWQiXQiiQimQinQioQitQi~O[aO~P#PORXOW]OX^OY_OZ`O[aOmVOnVOoWOUQiiQitQi~OTQi~P$OOTYO~P$OORXOY_OZ`O[aOmVOnVOTQiUQiWQiXQiiQitQi~OoQi~P%UOoWO~P%UOY_OZ`OTQiUQiXQiiQitQi~ORXOW]O[aOmVOnVOoWO~P&[OZ`ORQiTQiUQiWQiXQi[QiiQimQinQioQitQi~OYQi~P'ZO[Qi~P#PO^]krk~",
  goto: "#mrPPsP!SPP!]PPPPPPPPPPP!esPPsPPPP!tPPPs!ekUORTXYZ[]^_`ao_XPbfghij][PbfgijkSORTXYZ[]^_`aoQPOQbRQdTQeXQfYQgZQh[Qi]Qj^Qk_Ql`QmaRpo",
  nodeNames: "⚠ Expression BinaryExpression CompareOp CompareOp LogicOp LogicOp BitOp BitOp BitOp ArithOp ArithOp BitOp IntegerLiteral FloatingPointLiteral BooleanLiteral CharacterLiteral StringLiteral null ParenthesizedExpression UnaryExpression LogicOp BitOp CastExpression PrimitiveType",
  maxTerm: 36,
  nodeProps: [
    ["isolate", -2,16,17,""]
  ],
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "4o~RzX^#upq#uqr$jrs$wtu&Ouv&svw&xwx'Vxy)]yz)bz{&s{|)g}!O)g!O!P)l!P!Q&s!Q!R+s!R![-c!^!_1j!_!`1z!`!a2Q#Q#R2e#R#S&O#T#o&O#p#q2j#r#s2w#y#z#u$f$g#u$g#BY&O#BY#BZ2|#BZ$IS&O$IS$I_2|$I_$I|&O$I|$JO2|$JO$JT&O$JT$JU2|$JU$KV&O$KV$KW2|$KW&FU&O&FU&FV2|&FV;'S&O;'S;=`&m<%lO&O~#zYk~X^#upq#u#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#uR$oPeP!_!`$rQ$wORQ~$zWOY$wZr$wrs%ds#O$w#O#P%i#P;'S$w;'S;=`%x<%lO$w~%iOa~~%lSOY$wZ;'S$w;'S;=`%x<%lO$w~%{P;=`<%l$w~&TWr~tu&O!Q![&O!c!}&O#R#S&O#T#o&O$g;'S&O;'S;=`&m<%lO&O~&pP;=`<%l&O~&xOZ~~&}Po~vw'Q~'VOT~~'YVOY'oZw'ox#O'o#O#P'z#P;'S'o;'S;=`)V<%lO'o~'rPwx'u~'zO`~~'}WOY(gZw(gwx'ox#O(g#O#P'o#P;'S(g;'S;=`)P<%lO(g~(jVOY(gZw(gwx'ux#O(g#P;'S(g;'S;=`)P<%lO(g~)SP;=`<%l(g~)YP;=`<%l'o~)bOs~~)gOt~~)lOY~~)oP!Q![)r~)wW^~!Q![)r!f!g*a!g!h*f!h!i*a#R#S+j#W#X*a#X#Y*f#Y#Z*a~*fO^~~*iR{|*r}!O*r!Q![*x~*uP!Q![*x~*}U^~!Q![*x!f!g*a!h!i*a#R#S+a#W#X*a#Y#Z*a~+dQ!Q![*x#R#S+a~+mQ!Q![)r#R#S+j~+x_]~!O!P,w!Q![-c!d!e.i!f!g*a!g!h*f!h!i*a!n!o.Z!z!{/W#R#S.`#U#V.i#W#X*a#X#Y*f#Y#Z*a#`#a.Z#l#m/W~,|V^~!Q![)r!f!g*a!g!h*f!h!i*a#W#X*a#X#Y*f#Y#Z*a~-hZ]~!O!P,w!Q![-c!f!g*a!g!h*f!h!i*a!n!o.Z#R#S.`#W#X*a#X#Y*f#Y#Z*a#`#a.Z~.`O]~~.cQ!Q![-c#R#S.`~.lQ!Q!R.r!R!S.r~.wT]~!Q!R.r!R!S.r!n!o.Z#R#S.i#`#a.Z~/ZS!O!P/g!Q![0Y!c!i0Y#T#Z0Y~/jR!Q![/s!c!i/s#T#Z/s~/vU!Q![/s!c!i/s!r!s*f#R#S/g#T#Z/s#d#e*f~0_X]~!O!P0z!Q![0Y!c!i0Y!n!o.Z!r!s*f#R#S1^#T#Z0Y#`#a.Z#d#e*f~0}T!Q![/s!c!i/s!r!s*f#T#Z/s#d#e*f~1aR!Q![0Y!c!i0Y#T#Z0Y~1oQm~!^!_1u!_!`$r~1zO[~Q1}P!_!`$r~2VQn~!_!`$r!`!a2]~2bP[~!`!a1u~2jOX~~2oPW~#p#q2r~2wOU~~2|Of~~3Thk~r~X^#upq#utu&O!Q![&O!c!}&O#R#S&O#T#o&O#y#z#u$f$g#u$g#BY&O#BY#BZ2|#BZ$IS&O$IS$I_2|$I_$I|&O$I|$JO2|$JO$JT&O$JT$JU2|$JU$KV&O$KV$KW2|$KW&FU&O&FU&FV2|&FV;'S&O;'S;=`&m<%lO&O",
  tokenizers: [0, 1],
  topRules: {"Expression":[0,1]},
  specialized: [{term: 34, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 339
})
