// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Expression = 1,
  IntegerLiteral = 2,
  FloatingPointLiteral = 3,
  BooleanLiteral = 4,
  CharacterLiteral = 5,
  StringLiteral = 6,
  _null = 7
