// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  BlockComment = 1,
  Expression = 2,
  BinaryExpression = 3,
  times = 12,
  IntegerLiteral = 14,
  FloatingPointLiteral = 15,
  BooleanLiteral = 16,
  CharacterLiteral = 17,
  StringLiteral = 18,
  _null = 19,
  ParenthesizedExpression = 20,
  UnaryExpression = 21,
  CastExpression = 24,
  PrimitiveType = 25
