// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Expression = 1,
  UnaryExpression = 2,
  IntegerLiteral = 4,
  FloatingPointLiteral = 5,
  BooleanLiteral = 6,
  CharacterLiteral = 7,
  StringLiteral = 8,
  _null = 9
