// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,true:32, false:32, null:38, byte:50, short:50, int:50, long:50, char:50, float:50, double:50, boolean:50}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%^OVQPOOQwQQOOOOQO'#DO'#DOO!oQPO'#CpOOQO'#C}'#C}OVQPO'#CqOOQO'#Cy'#CyOOQO'#C`'#C`OOQO'#Cc'#CcOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xO!vQQO,59[O!}QPO,59`OOQO,59],59]O#}QQO1G.dO%PQQO1G.dO%WQQO1G.dO&YQQO1G.dO&aQQO1G.dO'SQQO1G.dO(eQQO1G.dOOQO1G.d1G.dO(lQQO1G.dOOQO1G.v1G.vOVQPO1G.zOOQO7+$f7+$f",
  stateData: "(y~OlOS~OYTO^QO_QO`QOaQObQOcQOfTOgTOtRO~ORXOTYOUZOW]OX^OY_OZ`O[`O]aOnVOoVOpWO~OicO~PVOunO~PwOuoO~OY_OZ`O[`ORQiTQiUQiWQiXQijQinQioQipQiuQi~O]aO~P#SORXOW]OX^OY_OZ`O[`O]aOnVOoVOpWOUQijQiuQi~OTQi~P$UOTYO~P$UORXOY_OZ`O[`O]aOnVOoVOTQiUQiWQiXQijQiuQi~OpQi~P%_OpWO~P%_OY_OZ`O[`OTQiUQiXQijQiuQi~ORXOW]O]aOnVOoVOpWO~P&hOZ`O[`ORQiTQiUQiWQiXQi]QijQinQioQipQiuQi~OYQi~P'jO]Qi~P#SO_^lsl~",
  goto: "#nsPPtP!TPP!^PPPPPPPPPPPP!ftPPtPPPP!uPPPt!fkUORTXYZ[]^_`ao_XPbfghij][PbfgijkSORTXYZ[]^_`aoQPOQbRQdTQeXQfYQgZQh[Qi]Qj^Qk_Ql`QmaRpo",
  nodeNames: "⚠ Expression BinaryExpression CompareOp CompareOp LogicOp LogicOp BitOp BitOp BitOp ArithOp ArithOp ArithOp BitOp IntegerLiteral FloatingPointLiteral BooleanLiteral CharacterLiteral StringLiteral null ParenthesizedExpression UnaryExpression LogicOp BitOp CastExpression PrimitiveType",
  maxTerm: 37,
  nodeProps: [
    ["isolate", -2,17,18,""]
  ],
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "4t~RzX^#upq#uqr$jrs$wtu&Ouv&svw&xwx'Vxy)]yz)bz{)g{|)l}!O)l!O!P)q!P!Q)g!Q!R+x!R![-h!^!_1o!_!`2P!`!a2V#Q#R2j#R#S&O#T#o&O#p#q2o#r#s2|#y#z#u$f$g#u$g#BY&O#BY#BZ3R#BZ$IS&O$IS$I_3R$I_$I|&O$I|$JO3R$JO$JT&O$JT$JU3R$JU$KV&O$KV$KW3R$KW&FU&O&FU&FV3R&FV;'S&O;'S;=`&m<%lO&O~#zYl~X^#upq#u#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#uR$oPfP!_!`$rQ$wORQ~$zWOY$wZr$wrs%ds#O$w#O#P%i#P;'S$w;'S;=`%x<%lO$w~%iOb~~%lSOY$wZ;'S$w;'S;=`%x<%lO$w~%{P;=`<%l$w~&TWs~tu&O!Q![&O!c!}&O#R#S&O#T#o&O$g;'S&O;'S;=`&m<%lO&O~&pP;=`<%l&O~&xO[~~&}Pp~vw'Q~'VOT~~'YVOY'oZw'ox#O'o#O#P'z#P;'S'o;'S;=`)V<%lO'o~'rPwx'u~'zOa~~'}WOY(gZw(gwx'ox#O(g#O#P'o#P;'S(g;'S;=`)P<%lO(g~(jVOY(gZw(gwx'ux#O(g#P;'S(g;'S;=`)P<%lO(g~)SP;=`<%l(g~)YP;=`<%l'o~)bOt~~)gOu~~)lOZ~~)qOY~~)tP!Q![)w~)|W_~!Q![)w!f!g*f!g!h*k!h!i*f#R#S+o#W#X*f#X#Y*k#Y#Z*f~*kO_~~*nR{|*w}!O*w!Q![*}~*zP!Q![*}~+SU_~!Q![*}!f!g*f!h!i*f#R#S+f#W#X*f#Y#Z*f~+iQ!Q![*}#R#S+f~+rQ!Q![)w#R#S+o~+}_^~!O!P,|!Q![-h!d!e.n!f!g*f!g!h*k!h!i*f!n!o.`!z!{/]#R#S.e#U#V.n#W#X*f#X#Y*k#Y#Z*f#`#a.`#l#m/]~-RV_~!Q![)w!f!g*f!g!h*k!h!i*f#W#X*f#X#Y*k#Y#Z*f~-mZ^~!O!P,|!Q![-h!f!g*f!g!h*k!h!i*f!n!o.`#R#S.e#W#X*f#X#Y*k#Y#Z*f#`#a.`~.eO^~~.hQ!Q![-h#R#S.e~.qQ!Q!R.w!R!S.w~.|T^~!Q!R.w!R!S.w!n!o.`#R#S.n#`#a.`~/`S!O!P/l!Q![0_!c!i0_#T#Z0_~/oR!Q![/x!c!i/x#T#Z/x~/{U!Q![/x!c!i/x!r!s*k#R#S/l#T#Z/x#d#e*k~0dX^~!O!P1P!Q![0_!c!i0_!n!o.`!r!s*k#R#S1c#T#Z0_#`#a.`#d#e*k~1ST!Q![/x!c!i/x!r!s*k#T#Z/x#d#e*k~1fR!Q![0_!c!i0_#T#Z0_~1tQn~!^!_1z!_!`$r~2PO]~Q2SP!_!`$r~2[Qo~!_!`$r!`!a2b~2gP]~!`!a1z~2oOX~~2tPW~#p#q2w~2|OU~~3ROg~~3Yhl~s~X^#upq#utu&O!Q![&O!c!}&O#R#S&O#T#o&O#y#z#u$f$g#u$g#BY&O#BY#BZ3R#BZ$IS&O$IS$I_3R$I_$I|&O$I|$JO3R$JO$JT&O$JT$JU3R$JU$KV&O$KV$KW3R$KW&FU&O&FU&FV3R&FV;'S&O;'S;=`&m<%lO&O",
  tokenizers: [0, 1],
  topRules: {"Expression":[0,1]},
  specialized: [{term: 35, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 357
})
